vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        ads_pictures:
            # alias for acced picture via navigator
            uri_prefix: /pictures/ads
            # path stokage directory
            upload_destination: '%kernel.project_dir%/public/pictures/ads'
            delete_on_update: true
            delete_on_remove: true

